// app/providers.tsx
"use client";
import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "./theme";
import { KindeProvider } from "@kinde-oss/kinde-auth-nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <KindeProvider>
      <ChakraProvider theme={theme}>{children}</ChakraProvider>
    </KindeProvider>
  );
}
